# Generated by Django 3.2.7 on 2021-09-25 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='groupList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gName', models.CharField(max_length=100, verbose_name='账号名称')),
                ('gID', models.CharField(max_length=100, verbose_name='账号ID')),
            ],
            options={
                'db_table': '账号列表',
            },
        ),
        migrations.CreateModel(
            name='artical',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('href', models.CharField(max_length=100, verbose_name='文章链接')),
                ('content', models.CharField(max_length=10000, verbose_name='文章内容')),
                ('group', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spyder.grouplist', verbose_name='所属账号')),
            ],
            options={
                'db_table': '文章列表',
            },
        ),
    ]
