# Generated by Django 3.2.7 on 2021-09-25 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spyder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artical',
            options={'verbose_name': '文章列表', 'verbose_name_plural': '文章列表'},
        ),
        migrations.AlterModelOptions(
            name='grouplist',
            options={'verbose_name': '账号信息', 'verbose_name_plural': '账号信息'},
        ),
        migrations.AlterModelTable(
            name='artical',
            table='artical',
        ),
        migrations.AlterModelTable(
            name='grouplist',
            table='groupList',
        ),
    ]
