# Generated by Django 3.2.7 on 2021-09-25 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spyder', '0002_auto_20210925_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artical',
            options={},
        ),
        migrations.AlterModelOptions(
            name='grouplist',
            options={},
        ),
    ]
